listen_addr = ":7076"
data_dir = "data"
flush_size = 10000
flush_time = 1
check_interval = 1
rewrite_interval = 10
conn_pool_size = 20
write_timeout = 10
write_tracing = false
query_tracing = false
token = ""
https_enabled = false
https_cert = ""
https_key = ""

[[circles]]
name = "circle-1"

[[circles.backends]]
name = "influxdb-1-1"
url = "http://127.0.0.1:8086"
token = ""

[[circles.backends]]
name = "influxdb-1-2"
url = "http://127.0.0.1:8087"
token = ""

[[circles]]
name = "circle-2"

[[circles.backends]]
name = "influxdb-2-1"
url = "http://127.0.0.1:8088"
token = ""

[[circles.backends]]
name = "influxdb-2-2"
url = "http://127.0.0.1:8089"
token = ""
